wallpaper {
  monitor = HDMI-A-1
  path = /home/blas/wallpapers/background.jpg
  fit_mode = cover
}
wallpaper {
  monitor =eDP-1
  path = /home/blas/wallpapers/background.jpg
  fit_mode = cover
}

#enable splash text rendering over the wallpaper
splash = true

# enable inter process communication
ipc = on
